import React from 'react'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const About = () => {
  return (
    <>

    {/* <heroSection/> */}
    {/* <secondSEc/> */}
    </>
  )
}

export default About